'use strict'

const fs = require('fs')
const path = require('path')
const log = require('fancy-log')

/**
 * Assembles js/vendor/prism/prism-core.js from the prismjs package: the core,
 * the grammars listed in gulp.d/prism-languages.js in dependency order, and
 * the keep-markup plugin (11-editable-placeholders.js relies on it to keep the
 * editable spans inside highlighted code). Same shape as the file the
 * prismjs.com download page produced, minus the 190 grammars nobody used.
 *
 * Runs as part of bundle:build and preview:build. The output is generated,
 * not tracked: bump prismjs or edit the language list and rebuild.
 *
 * @param {string} outFile - Path of the file to write.
 * @returns {Function} Gulp task.
 */
module.exports = (outFile) => () => {
  const components = require('prismjs/components.json')
  const getLoader = require('prismjs/dependencies')
  const languages = require('../prism-languages')
  const pkg = require('prismjs/package.json')
  const base = path.dirname(require.resolve('prismjs/package.json'))

  const unknown = languages.filter((id) => !components.languages[id])
  if (unknown.length) throw new Error(`prism-languages.js lists grammars prismjs does not have: ${unknown.join(', ')}`)

  const ids = getLoader(components, languages.concat('keep-markup')).getIds()
  const files = ['components/prism-core.min.js'].concat(
    ids.map((id) =>
      components.plugins[id]
        ? `plugins/${id}/prism-${id}.min.js`
        : `components/prism-${id}.min.js`
    )
  )
  const header =
    `/* eslint-disable */\n/* PrismJS ${pkg.version}: core + ${ids.filter((id) => components.languages[id]).length} grammars + keep-markup, ` +
    'generated by gulp.d/tasks/generate-prism.js from gulp.d/prism-languages.js. Do not edit. */\n'
  const body = files.map((f) => fs.readFileSync(path.join(base, f), 'utf8').trim()).join('\n')
  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, header + body + '\n')
  log.info(`Built ${path.basename(outFile)}: ${ids.length} components, ${Math.round(fs.statSync(outFile).size / 1024)} KiB`)
  return Promise.resolve()
}
