name: Update Go modules

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-go-mod]

jobs:
  update-go-modules:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RP_AWS_CRED_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}

      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
          parse-json-secrets: true

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          path: redpanda-docs
          token: ${{ env.ACTIONS_BOT_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Wait for registry update
        run: sleep 300

      - name: Update dependencies
        run: |
          cd ./redpanda-docs/blobl-editor/wasm
          go get -u ./...
          go mod tidy

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "auto-docs: Update Go modules"
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          path: redpanda-docs
          branch: update-go-mod
          title: "auto-docs: Update Go modules"
          body: |
            This PR updates the Go modules for the Bloblang playground Wasm code.
          labels: auto-docs
          reviewers: JakeSCahill
